#!/usr/bin/python
# -*- coding: latin-1 -*-

shortname = "lorem"
program = "Lorem Ipsum Generator (%s)" % shortname
version = "0.7.0"
copyright = "Copyright (C) 2007 Per Erik Strandberg"
license = """This is free software, and you are welcome to redistribute it
under the GNU General Public License <http://www.gnu.org/licenses/gpl.html>
%s comes with NO WARRANTY, to the extent permitted by law.""" % shortname


# Copyright 2007 Per Erik Strandberg: <per at pererikstrandberg dot se>
#
# This program is free software you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.


# Thanks to
#  * Barre, for the n overflow solution
#  * http://lipsum.sourceforge.net/whatis.php for source lorems and inspiration
#  * The EMACS spook function


from string import join

def get_lorem(q = 0):
    i = -1

    i += 1
    if q == i:
        #This text is under public domain
        #Lorem ipsum
        #Cicero
        return u"""lorem ipsum dolor sit amet consetetur sadipscing elitr sed diam nonumy
eirmod tempor invidunt ut labore et dolore magna aliquyam erat sed diam
voluptua at vero eos et accusam et justo duo dolores et ea rebum stet clita
kasd gubergren no sea takimata sanctus est lorem ipsum dolor sit amet lorem
ipsum dolor sit amet consetetur sadipscing elitr sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat sed diam voluptua at
vero eos et accusam et justo duo dolores et ea rebum stet clita kasd
gubergren no sea takimata sanctus est lorem ipsum dolor sit amet lorem ipsum
dolor sit amet consetetur sadipscing elitr sed diam nonumy eirmod tempor
invidunt ut labore et dolore magna aliquyam erat sed diam voluptua at vero
eos et accusam et justo duo dolores et ea rebum stet clita kasd gubergren no
sea takimata sanctus est lorem ipsum dolor sit amet

duis autem vel eum iriure dolor in hendrerit in vulputate velit esse
molestie consequat vel illum dolore eu feugiat nulla facilisis at vero eros
et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril
delenit augue duis dolore te feugait nulla facilisi lorem ipsum dolor sit
amet consectetuer adipiscing elit sed diam nonummy nibh euismod tincidunt ut
laoreet dolore magna aliquam erat volutpat

ut wisi enim ad minim veniam quis nostrud exerci tation ullamcorper suscipit
lobortis nisl ut aliquip ex ea commodo consequat duis autem vel eum iriure
dolor in hendrerit in vulputate velit esse molestie consequat vel illum
dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio
dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te
feugait nulla facilisi

nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet
doming id quod mazim placerat facer possim assum lorem ipsum dolor sit amet
consectetuer adipiscing elit sed diam nonummy nibh euismod tincidunt ut
laoreet dolore magna aliquam erat volutpat ut wisi enim ad minim veniam quis
nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea
commodo consequat

duis autem vel eum iriure dolor in hendrerit in vulputate velit esse
molestie consequat vel illum dolore eu feugiat nulla facilisis

at vero eos et accusam et justo duo dolores et ea rebum stet clita kasd
gubergren no sea takimata sanctus est lorem ipsum dolor sit amet lorem ipsum
dolor sit amet consetetur sadipscing elitr sed diam nonumy eirmod tempor
invidunt ut labore et dolore magna aliquyam erat sed diam voluptua at vero
eos et accusam et justo duo dolores et ea rebum stet clita kasd gubergren no
sea takimata sanctus est lorem ipsum dolor sit amet lorem ipsum dolor sit
amet consetetur sadipscing elitr at accusam aliquyam diam diam dolore
dolores duo eirmod eos erat et nonumy sed tempor et et invidunt justo labore
stet clita ea et gubergren kasd magna no rebum sanctus sea sed takimata ut
vero voluptua est lorem ipsum dolor sit amet lorem ipsum dolor sit amet
consetetur sadipscing elitr sed diam nonumy eirmod tempor invidunt ut labore
et dolore magna aliquyam erat

consetetur sadipscing elitr sed diam nonumy eirmod tempor invidunt ut labore
et dolore magna aliquyam erat sed diam voluptua at vero eos et accusam et
justo duo dolores et ea rebum stet clita kasd gubergren no sea takimata
sanctus est lorem ipsum dolor sit amet lorem ipsum dolor sit amet consetetur
sadipscing elitr sed diam nonumy eirmod tempor invidunt ut labore et dolore
magna aliquyam erat sed diam voluptua at vero eos et accusam et justo duo
dolores et ea rebum stet clita kasd gubergren no sea takimata sanctus est
lorem ipsum dolor sit amet lorem ipsum dolor sit amet consetetur sadipscing
elitr sed diam nonumy eirmod tempor invidunt ut labore et dolore magna
aliquyam erat sed diam voluptua at vero eos et accusam et justo duo dolores
et ea rebum stet clita kasd gubergren no sea takimata sanctus est lorem
ipsum dolor sit amet"""

    i += 1
    if q == i:
        #This text is under public domain
        #Childe Harold's Pilgrimage - Canto the first (I.-X.)
        #Lord Byron
        return u"""oh thou in hellas deemed of heavenly birth
muse formed or fabled at the minstrels will
since shamed full oft by later lyres on earth
mine dares not call thee from thy sacred hill
yet there ive wandered by thy vaunted rill
yes sighed oer delphis longdeserted shrine
where save that feeble fountain all is still
nor mote my shell awake the weary nine
to grace so plain a talethis lowly lay of mine

whilome in albions isle there dwelt a youth
who ne in virtues ways did take delight
but spent his days in riot most uncouth
and vexed with mirth the drowsy ear of night
ah me in sooth he was a shameless wight
sore given to revel and ungodly glee
few earthly things found favour in his sight
save concubines and carnal companie
and flaunting wassailers of high and low degree

childe harold was he hight but whence his name
and lineage long it suits me not to say
suffice it that perchance they were of fame
and had been glorious in another day
but one sad losel soils a name for aye
however mighty in the olden time
nor all that heralds rake from coffined clay
nor florid prose nor honeyed lines of rhyme
can blazon evil deeds or consecrate a crime

childe harold basked him in the noontide sun
disporting there like any other fly
nor deemed before his little day was done
one blast might chill him into misery
but long ere scarce a third of his passed by
worse than adversity the childe befell
he felt the fulness of satiety
then loathed he in his native land to dwell
which seemed to him more lone than eremites sad cell

for he through sins long labyrinth had run
nor made atonement when he did amiss
had sighed to many though he loved but one
and that loved one alas could neer be his
ah happy she to scape from him whose kiss
had been pollution unto aught so chaste
who soon had left her charms for vulgar bliss
and spoiled her goodly lands to gild his waste
nor calm domestic peace had ever deigned to taste

and now childe harold was sore sick at heart
and from his fellow bacchanals would flee
tis said at times the sullen tear would start
but pride congealed the drop within his ee
apart he stalked in joyless reverie
and from his native land resolved to go
and visit scorching climes beyond the sea
with pleasure drugged he almost longed for woe
and een for change of scene would seek the shades below

the childe departed from his fathers hall
it was a vast and venerable pile
so old it seemed only not to fall
yet strength was pillared in each massy aisle
monastic dome condemned to uses vile
where superstition once had made her den
now paphian girls were known to sing and smile
and monks might deem their time was come agen
if ancient tales say true nor wrong these holy men

yet ofttimes in his maddest mirthful mood
strange pangs would flash along childe harolds brow
as if the memory of some deadly feud
or disappointed passion lurked below
but this none knew nor haply cared to know
for his was not that open artless soul
that feels relief by bidding sorrow flow
nor sought he friend to counsel or condole
whateer this grief mote be which he could not control

and none did love him  though to hall and bower
he gathered revellers from far and near
he knew them flatterers of the festal hour
the heartless parasites of present cheer
yea none did love himnot his lemans dear
but pomp and power alone are womans care
and where these are light eros finds a feere
maidens like moths are ever caught by glare
and mammon wins his way where seraphs might despair

childe harold had a mothernot forgot
though parting from that mother he did shun
a sister whom he loved but saw her not
before his weary pilgrimage begun
if friends he had he bade adieu to none
yet deem not thence his breast a breast of steel
ye who have known what tis to dote upon
a few dear objects will in sadness feel
such partings break the heart they fondly hope to heal"""

    i += 1
    if q == i:
        #This text is under public domain
        #Decameron - Novella Prima
        #Giovanni Boccaccio
        return u"""convenevole cosa e carissime donne che ciascheduna cosa la quale l'uomo fa
dallo ammirabile e santo nome di colui il quale di tutte fu facitore le dea
principio per che dovendo io al vostro novellare sí come primo dare
cominciamento intendo da una delle sue maravigliose cose incominciare accio
che quella udita la nostra speranza in lui sí come in cosa impermutabile si
fermi e sempre sia da noi il suo nome lodato manifesta cosa e che sí come le
cose temporali tutte sono transitorie e mortali cosí in sé e fuor di sé
esser piene di noia d'angoscia e di fatica e a infiniti pericoli sogiacere
alle quali senza niuno fallo né potremmo noi che viviamo mescolati in esse e
che siamo parte d'esse durare né ripararci se spezial grazia di dio forza e
avvedimento non ci prestasse la quale a noi e in noi non e da credere che
per alcun nostro merito discenda ma dalla sua propria benignita mossa e da'
prieghi di coloro impetrata che sí come noi siamo furon mortali e bene i
suoi piaceri mentre furono in vita seguendo ora con lui eterni son divenuti
e beati alli quali noi medesimi sí come a procuratori informati per
esperienza della nostra fragilita forse non audaci di porgere i prieghi
nostri nel cospetto di tanto giudice delle cose le quali a noi reputiamo
oportune gli porgiamo e ancora piú in lui verso noi di pietosa liberalita
pieno discerniamo che non potendo l'acume dell'occhio mortale nel segreto
della divina mente trapassare in alcun modo avvien forse tal volta che da
oppinione ingannati tale dinanzi alla sua maesta facciamo procuratore che da
quella con etterno essilio e iscacciato e nondimeno esso al quale niuna cosa
e occulta piú alla purita del pregator riguardando che alla sua ignoranza o
allo essilio del pregato cosí come se quegli fosse nel suo cospetto beato
essaudisce coloro che 'l priegano il che manifestamente potra apparire nella
novella la quale di raccontare intendo manifestamente dico non il giudicio
di dio ma quel degli uomini seguitando"""

    i += 1
    if q == i:
        #This text is under public domain
        #Faust: Der Tragödie erster Teil
        #Johann Wolfgang von Goethe
        return u"""ihr naht euch wieder schwankende gestalten
die früh sich einst dem trüben blick gezeigt
versuch ich wohl euch diesmal festzuhalten
fühl ich mein herz noch jenem wahn geneigt
ihr drängt euch zu  nun gut so mögt ihr walten
wie ihr aus dunst und nebel um mich steigt
mein busen fühlt sich jugendlich erschüttert
vom zauberhauch der euren zug umwittert

ihr bringt mit euch die bilder froher tage
und manche liebe schatten steigen auf
gleich einer alten halbverklungnen sage
kommt erste lieb und freundschaft mit herauf
der schmerz wird neu es wiederholt die klage
des lebens labyrinthisch irren lauf
und nennt die guten die um schöne stunden
vom glück getäuscht vor mir hinweggeschwunden

sie hören nicht die folgenden gesänge
die seelen denen ich die ersten sang
zerstoben ist das freundliche gedränge
verklungen ach  der erste widerklang
mein lied ertönt der unbekannten menge
ihr beifall selbst macht meinem herzen bang
und was sich sonst an meinem lied erfreuet
wenn es noch lebt irrt in der welt zerstreuet

und mich ergreift ein längst entwöhntes sehnen
nach jenem stillen ernsten geisterreich
es schwebet nun in unbestimmten tönen
mein lispelnd lied der äolsharfe gleich
ein schauer faßt mich träne folgt den tränen
das strenge herz es fühlt sich mild und weich
was ich besitze seh ich wie im weiten
und was verschwand wird mir zu wirklichkeiten"""

    i += 1
    if q == i:
        #This text is under public domain
        #In der Fremde
        #Heinrich Heine
        return u"""es treibt dich fort von ort zu ort
du weißt nicht mal warum
im winde klingt ein sanftes wort
schaust dich verwundert um

die liebe die dahinten blieb
sie ruft dich sanft zurück
o komm zurück ich hab dich lieb
du bist mein einz'ges glück

doch weiter weiter sonder rast
du darfst nicht stillestehn
was du so sehr geliebet hast
sollst du nicht wiedersehn

du bist ja heut so grambefangen
wie ich dich lange nicht geschaut
es perlet still von deinen wangen
und deine seufzer werden laue

denkst du der heimat die so ferne
so nebelferne dir verschwand
gestehe mir's du wärest gerne
manchmal im teuren vaterland

denkst du der dame die so niedlich
mit kleinem zürnen dich ergötzt
oft zürntest du dann ward sie friedlich
und immer lachtet ihr zuletzt

denkst du der freunde die da sanken
an deine brust in großer stund'
im herzen stürmten die gedanken
jedoch verschwiegen blieb der mund

denkst du der mutter und der schwester
mit beiden standest du ja gut
ich glaube gar es schmilzt mein bester
in deiner brust der wilde mut

denkst du der vögel und der bäume
des schönen gartens wo du oft
geträumt der liebe junge träume
wo du gezagt wo du gehofft

es ist schon spät die nacht ist helle
trübhell gefärbt vom feuchten schnee
ankleiden muß ich mich nun schnelle
und in gesellschaft gehn o weh"""

    i += 1
    if q == i:
        #This text is under public domain
        #Le Bateau Ivre
        #Arthur Baudelaire
        return u"""comme je descendais des fleuves impassibles
je ne me sentis plus guidé par les haleurs
des peaux-rouges criards les avaient pris pour cibles
les ayant cloués nus aux poteaux de couleurs

j'étais insoucieux de tous les équipages
porteur de blés flamands ou de cotons anglais
quand avec mes haleurs ont fini ces tapages
les fleuves m'ont laissé descendre ou je voulais

dans les clapotements furieux des marées
moi l'autre hiver plus sourd que les cerveaux d'enfants
je courus  et les péninsules démarrées
n'ont pas subi tohu-bohus plus triomphants

la tempete a béni mes éveils maritimes
plus léger qu'un bouchon j'ai dansé sur les flots
qu'on appelle rouleurs éternels de victimes
dix nuits sans regretter l'oeil niais des falots

plus douce qu'aux enfants la chair des pommes sures
l'eau verte pénétra ma coque de sapin
et des taches de vins bleus et des vomissures
me lava dispersant gouvernail et grappin

et des lors je me suis baigné dans le poeme
de la mer infusé d'astres et lactescent
dévorant les azurs verts  ou flottaison bleme
et ravie un noyé pensif parfois descend

ou teignant tout a coup les bleuités délires
et rythmes lents sous les rutilements du jour
plus fortes que l'alcool plus vastes que nos lyres
fermentent les rousseurs ameres de l'amour

je sais les cieux crevant en éclairs et les trombes
et les ressacs et les courants  je sais le soir
l'aube exaltée ainsi qu'un peuple de colombes
et j'ai vu quelque fois ce que l'homme a cru voir

j'ai vu le soleil bas taché d'horreurs mystiques
illuminant de longs figements violets
pareils a des acteurs de drames tres-antiques
les flots roulant au loin leurs frissons de volets

j'ai revé la nuit verte aux neiges éblouies
baiser montant aux yeux des mers avec lenteurs
la circulation des seves inouies
et l'éveil jaune et bleu des phosphores chanteurs

j'ai suivi des mois pleins pareille aux vacheries
hystériques la houle a l'assaut des récifs
sans songer que les pieds lumineux des maries
pussent forcer le mufle aux océans poussifs

j'ai heurté savez-vous d'incroyables florides
melant aux fleurs des yeux de pantheres a peaux
d'hommes  des arcs-en-ciel tendus comme des brides
sous l'horizon des mers a de glauques troupeaux

j'ai vu fermenter les marais énormes nasses
ou pourrit dans les joncs tout un léviathan
des écroulement d'eau au milieu des bonaces
et les lointains vers les gouffres cataractant

glaciers soleils d'argent flots nacreux cieux de braises
échouages hideux au fond des golfes bruns
ou les serpents géants dévorés de punaises
choient des arbres tordus avec de noirs parfums

j'aurais voulu montrer aux enfants ces dorades
du flot bleu ces poissons d'or ces poissons chantants
- des écumes de fleurs ont bercé mes dérades
et d'ineffables vents m'ont ailé par instants

parfois martyr lassé des pôles et des zones
la mer dont le sanglot faisait mon roulis doux
montait vers moi ses fleurs d'ombres aux ventouses jaunes
et je restais ainsi qu'une femme a genoux

presque île balottant sur mes bords les querelles
et les fientes d'oiseaux clabaudeurs aux yeux blonds
et je voguais lorsqu'a travers mes liens freles
des noyés descendaient dormir a reculons

or moi bateau perdu sous les cheveux des anses
jeté par l'ouragan dans l'éther sans oiseau
moi dont les monitors et les voiliers des hanses
n'auraient pas repeché la carcasse ivre d'eau

libre fumant monté de brumes violettes
moi qui trouais le ciel rougeoyant comme un mur
qui porte confiture exquise aux bons poetes
des lichens de soleil et des morves d'azur

qui courais taché de lunules électriques
planche folle escorté des hippocampes noirs
quand les juillets faisaient crouler a coups de triques
les cieux ultramarins aux ardents entonnoirs

moi qui tremblais sentant geindre a cinquante lieues
le rut des béhémots et les maelstroms épais
fileur éternel des immobilités bleues
je regrette l'europe aux anciens parapets

j'ai vu des archipels sidéraux  et des îles
dont les cieux délirants sont ouverts au vogueur
- est-ce en ces nuits sans fond que tu dors et t'exiles
million d'oiseaux d'or ô future vigueur  -

mais vrai j'ai trop pleuré  les aubes sont navrantes
toute lune est atroce et tout soleil amer
l'âcre amour m'a gonflé de torpeurs enivrantes
ô que ma quille éclate  ô que j'aille a la mer

si je désire une eau d'europe c'est la flache
noire et froide ou vers le crépuscule embaumé
un enfant accroupi plein de tristesses lâche
un bateau frele comme un papillon de mai

je ne puis plus baigné de vos langueurs ô lames
enlever leur sillage aux porteurs de cotons
ni traverser l'orgueil des drapeaux et des flammes
ni nager sous les yeux horribles des pontons"""

    i += 1
    if q == i:
        #This text is under public domain
        #Le Masque
        #Arthur Rembaud
        return u"""contemplons ce trésor de grâces florentines
dans l'ondulation de ce corps musculeux
l'elégance et la force abondent soeurs divines
cette femme morceau vraiment miraculeux
divinement robuste adorablement mince
est faite pour trôner sur des lits somptueux
et charmer les loisirs d'un pontife ou d'un prince

aussi vois ce souris fin et voluptueux
ou la fatuité promene son extase
ce long regard sournois langoureux et moqueur
ce visage mignard tout encadré de gaze
dont chaque trait nous dit avec un air vainqueur
«la volupté m'appelle et l'amour me couronne»
a cet etre doué de tant de majesté
vois quel charme excitant la gentillesse donne
approchons et tournons autour de sa beauté

ô blaspheme de l'art ô surprise fatale
la femme au corps divin promettant le bonheur
par le haut se termine en monstre bicéphale

mais non ce n'est qu'un masque un décor suborneur
ce visage éclairé d'une exquise grimace
et regarde voici crispée atrocement
la véritable tete et la sincere face
renversée a l'abri de la face qui ment
pauvre grande beauté le magnifique fleuve
de tes pleurs aboutit dans mon coeur soucieux
ton mensonge m'enivre et mon âme s'abreuve
aux flots que la douleur fait jaillir de tes yeux

mais pourquoi pleure-t-elle elle beauté parfaite
qui mettrait a ses pieds le genre humain vaincu
quel mal mystérieux ronge son flanc d'athlete

elle pleure insensé parce qu'elle a vécu
et parce qu'elle vit mais ce qu'elle déplore
surtout ce qui la fait frémir jusqu'aux genoux
c'est que demain hélas il faudra vivre encore
demain apres-demain et toujours  comme nous"""

    i += 1
    if q == i:
        #This text is under public domain
        #Nagyon fáj
        #József Attila
        return u"""kivül belõl
leselkedõ halál elõl
mint lukba megriadt egérke

amíg hevülsz
az asszonyhoz úgy menekülsz
hogy óvjon karja öle térde

nemcsak a lágy
meleg öl csal nemcsak a vágy
de odataszít a muszáj is

ezért ölel
minden ami asszonyra lel
míg el nem fehérül a száj is

kettõs teher
s kettõs kincs hogy szeretni kell
ki szeret s párra nem találhat

oly hontalan
mint amilyen gyámoltalan
a szükségét végzõ vadállat

nincsen egyéb
menedékünk a kés hegyét
bár anyádnak szegezd te bátor

és lásd akadt
nõ ki érti e szavakat
de mégis ellökött magától

nincsen helyem
így élõk közt zúg a fejem
gondom s fájdalmam kicifrázva

mint a gyerek
kezében a csörgõ csereg
ha magára hagyottan rázza

mit kellene
tenni érte és ellene
nem szégyellem ha kitalálom

hisz kitaszít
a világ így is olyat akit
kábít a nap rettent az álom

a kultúra
úgy hull le rólam mint ruha
másról a boldog szerelemben

de az hol áll
hogy nézze mint dobál halál
s még egyedül kelljen szenvednem

a csecsemõ
is szenvedi ha szül a nõ
páros kínt enyhíthet alázat

de énnekem
pénzt hoz fájdalmas énekem
s hozzám szegõdik a gyalázat

segítsetek
ti kisfiúk a szemetek
pattanjon meg ott õ ahol jár

ártatlanok
csizmák alatt sikongjatok
és mondjátok neki¨nagyon fáj

ti hû ebek
kerék alá kerüljetek
s ugassátok neki nagyon fáj

nõk terhetek
viselõk elvetéljetek
és sírjátok neki nagyon fáj

ép emberek
bukjatok öszetörjetek
s motyogjatok neki nagyon fáj

ti férfiak
egymást megtépve nõ miatt
ne hallgassátok el nagyon fáj

lovak bikák
kiket hogy húzzatok igát
herélnek ríjjátok nagyon fáj

néma halak
horgot kapjatok jég alatt
és tátogjatok rá nagyon fáj

elevenek
minden mi kíntól megremeg
égjen hol laktok kert vadon táj

s ágya körül
üszkösen ha elszenderül
vakogjatok velem nagyon fáj

hallja míg él
azt tagadta meg amit ér
elvonta puszta kénye végett

kivül belõl
menekülõ élõ elõl
a legutolsó menedéket"""

    i += 1
    if q == i:
        #This text is under public domain
        #Ómagyar-Mária siralom
        #Ismeretlen
        return u"""volek syrolm thudothlon syrolmol sepedyk buol ozuk epedek walasth vylagumtul
sydou fyodumtul ezes urumemtuul o en eses urodum eggen yg fyodum syrou aniath
thekunched buabeleul kyniuhhad scemem kunuel arad en iunhum buol farad the
werud hullothya en iunhum olelothya vylag uilaga viragnac uiraga keseruen
kynzathul uos scegegkel werethul vh nequem en fyon ezes mezuul scegenul
scepsegud wirud hioll wyzeul syrolmom fuhazatum therthetyk kyul en iumhumnok
bel bua qui sumha nym kyul hyul wegh halal engumet eggedum illen maraggun
urodum kyth wylag felleyn o ygoz symeonnok bezzeg scouuo ere en erzem ez
buthuruth kyt niha egyre tuled ualmun de num ualallal hul yg kynzassal fyom
halallal sydou myth thez turuentelen fyom merth hol byuntelen fugwa huztuzwa
wklelue kethwe ulud keguggethuk fyomnok ne leg kegulm mogomnok owog halal
kynaal anyath ezes fyaal egembelu ullyetuk"""

    i += 1
    if q == i:
        #This text is under public domain
        #Robinsono Kruso (Esperanto)
        #Daniel Defoe
        return u"""mi naskigxis en jorko anglujo je marto kiu estas la
sesjarrego de la regxo karolo la unua infane mi sentadis grandan
deziron por pasigi mian vivon sur la maro kaj pliagxante la deziro
plifortigxis gxis fine mi forlasis mian lernejon kaj hejmon kaj
piede mi trovis mian vojon al hull kie mi baldaux trovis okupadon sur
sxipo

post kiam ni velveturis kelke da tagoj okazis ventego kaj kvinanokte
la sxipo enfendigxis cxiuj al la pumpiloj rapidis la sxipon ni sentis
gxemi en cxiuj siaj tabuloj kaj gxian trabajxon ektremi de la antauxa gxis
la posta parto kaj baldaux klarigxis ke ne estas ia espero por gxi kaj
ke cxio kion ni povas fari estas savi niajn vivojn

unue ni pafadis pafilegojn por venigi helpon kaj post kelke da
tempo sxipo kusxante ne malproksime alsendis boaton por helpi nin sed
la maro estis tro maltrankvila por gxi restadi sxipflanke tial ni
eljxetis sxnuregon kiun la boatanoj ekkaptis kaj firme fiksis kaj
tiamaniere ni cxiuj enboatigxis

tamen vanigxis en tia maltrankvila maro por peni albordigxi la sxipon
kiu alsendis la virojn aux aluzi la remilojn de la boato kaj ni ne
povis ion fari krom gxin lasi peligxi teron

duonhore nia sxipo trafis rifon kaj subakvigxis kaj gxin ni ne vidis
plu tre malrapide ni alproksimigxis teron kiun iafoje ni vidis kiam
ajn la boato levigxis sur la supro de ia alta ondo kaj tie ni vidis
homojn kurante amase tien kaj reen havante unu celon savi nin

fine gxojege ni surterigxis kie bonsxance ni renkontis amikojn kiuj
donis al ni helpon por reveturi al hull kaj se tiam mi havus la
bonan sencon por iri hejmon estus pli bone por mi

la viro kies sxipo subakvigxis diris kun grava mieno junulo ne iru
plu surmaron tiu ne estas la vivmaniero por vi kial do sinjoro
vi mem iros plu surmaron tiu estas alia afero mi estas elnutrita
por la maro sed vi ne estas vi venis sur mian sxipon por eltrovi la
staton de vivo surmara kaj vi povas diveni tion kio okazos al vi se
vi ne reiros hejmon dio ne benos vin kaj eble vi kauxzis tiun-cxi
tutan malbonon al ni

mi ne parolis alian vorton al li kiun vojon li iris mi nek scias
nek deziris sciigxi cxar mi estis ofendita pro tiu-cxi malgxentila
parolado mi multe pensis cxu iri hejmon aux cxu iradi surmaron honto
detenis min pri iri hejmon kaj mi ne povis decidi la vivkuron kiun
mi estis ironta

kiel estis mia sorto travive cxiam elekti la plej malbonon tiel same
mi nun faris mi havis oron en mia monujo kaj bonan vestajxon sur mia
korpo sed surmaron mi ree iris

sed nun mi havis pli malbonan sxancon ol iam cxar kiam ni estis tre
malproksime enmaro kelke da turkoj en sxipeto plencxase alproksimigxis
al ni ni levis tiom da veloj kiom niaj velstangoj povis elporti por
ke ni forkuru de ili tamen malgraux tio ni vidis ke niaj malamikoj
pli kaj pli alproksimigxis kaj certigxis ke baldaux ili atingos nian
sxipon

fine ili atingis nin sed ni direktis niajn pafilegojn sur ilin kio
kauxzis portempe ke ili deflanku sian vojon sed ili dauxrigis pafadon
sur ni tiel longe kiel ili estis en pafspaco proksimigxante la duan
fojon kelkaj viroj atingis la ferdekon de nia sxipo kaj ektrancxis la
velojn kaj ekfaris cxiuspecajn difektajxojn tial post kiam dek el
niaj sxipanoj kusxas mortitaj kaj la plimulto el la ceteraj havas
vundojn ni kapitulacis

la cxefo de la turkoj prenis min kiel sian rabajxon al haveno okupita
de mauxroj li ne agis al mi tiel malbone kiel mi lin unue jugxis sed
li min laborigis kun la ceteraj de siaj sklavoj tio estis sxangxo en
mia vivo kiun mi neniam antauxvidis ho ve kiom mia koro malgxojis
pensante pri tiuj kiujn mi lasis hejme al kiuj mi ne montris tiom da
komplezemo kiom diri adiauxi kiam mi iris surmaron aux sciigi tion
kion mi intencas fari

tamen cxio kion mi travivis tiam estas nur antauxgusto de la penadoj
kaj zorgoj kiujn de tiam estis mia sorto suferi

unue mi pensis ke la turko kunprenos min kun si kiam li ree iros
surmaron kaj ke mi iel povos liberigxi sed la espero nelonge dauxris
cxar tiatempe li lasis min surtere por prizorgi liajn rikoltojn
tiamaniere mi vivis du jarojn tamen la turko konante kaj vidante min
plu min pli kaj pli liberigis li unufoje aux dufoje cxiusemajne
veturis en sia boato por kapti iajn platfisxojn kaj iafoje li
kunprenis min kaj knabon kun si cxar ni estas rapidaj cxe tia sporto
kaj tial li pli kaj pli sxatis min

unu tagon la turko elsendis min viron kaj knabon boate por kapti
kelke da fisxoj surmare okazas tia densa nebulo ke dekduhore ni ne
povas vidi la teron kvankam ni ne estas pli ol duonmejlon 00
metrojn de la terbordo kaj morgauxtage kiam la suno levigxis nia
boato estas enmaro almenaux dek mejlojn  kilometrojn de la
terbordo la vento vigle blovis kaj ni cxiuj tre bezonis nutrajxon sed
fine per la helpo de remiloj kaj veloj ni sendangxere reatingis la
terbordon

kiam la turko sciigxis kiamaniere ni vojperdis li diris ke de nun
kiam li velveturos li prenos boaton kiu enhavos cxion kion ni
bezonus se ni longatempe estus detenataj surmare tial li farigis
grandan kajuton en la longboato de sia sxipo kiel ankaux cxambron por ni
sklavoj unu tagon li min sendis por ke mi ordigu la boaton pro tio
ke li havas du amikojn kiuj intencas veturi kun li por fisxkapti sed
kiam la tempo alvenis ili ne veturas tial li sendis min viron kaj
knabon -- kies nomo estas zuro -- por kapti kelke da fisxoj por la
gastoj kiuj estas vespermangxontaj kun li

subite eniris en mian kapon la ideo ke nun estas bona okazo boate
forkuri kaj liberigxi tial mi tuj prenis tiom da nutrajxo kiom mi
povas havigi kaj mi diris al la viro ke estus tro malrespekte
mangxante la panon metitan en la boaton por la turko li diris ke li
pensas tiel same tial li alportis sakon da rizo kaj kelke da ruskoj
kukoj

dum la viro estis surtere mi provizis iom da vino pecegon da vakso
segilon hakilon fosilon iom da sxnurego kaj cxiuspecajn objektojn
kiuj eble estos utilaj al ni mi sciis kie trovigxas la vinkesto de la
turko kaj mi gxin metis surboaton dum la viro estas surtere per alia
ruzo mi havigis cxion kion mi bezonis mi diris al la knabo la
pafiloj de la turko estas en la boato sed ne trovigxas ia pafajxo cxu
vi pensas ke vi povas havigi iom da gxi vi scias kie gxi estas
konservata kaj eble ni volos pafi birdon aux du li do alportis kesto
kaj saketon kiuj enhavas cxion kion ni eble bezonas por la pafiloj
tiujn-cxi mi metis surboaton kaj poste velveturis por fisxkapti

la vento blovis de la nordo aux nordokcidento tia vento estis malbona
por mi cxar se gxi estus de la sudo mi estus povinta velveturi al la
terbordo de hispanujo tamen de kiu ajn loko la vento blovos mi
estis decidinta forkuri kaj lasi la ceterajn al ilia sorto mi do
mallevis miajn hokfadenojn kvazaux fisxkapti sed mi zorgis ke mi havu
malbonan sukceson kaj kiam la fisxoj mordis mi ilin ne eltiris cxar
mi deziris ke la mauxro ilin ne vidu mi diris al li tiu-cxi loko
estas nebona ni ne kaptos fisxojn tie-cxi ni devas iom antauxen iri
nu la mauxro pensis ke tion fari ne estos malbone li levis la
velojn kaj cxar la direktilo estis en miaj manoj mi elsendis la
boaton unu mejlon aux plu enmaron kaj poste gxin haltigis kvazaux mi
intencas fisxkapti

nun mi pripensis tiu-cxi estas mia okazo liberigxi tial mi transdonis
la direktilon al la knabo kaj tiam ekprenis la mauxron cxirkaux la
talio kaj eljxetis lin el la boato

malsupren li falis sed baldaux reaperis por ke li povis nagxi kvazaux
anaso li diris ke li volonte irus cxirkaux la mondo kun mi se mi
enprenus lin

iom timante ke li surrampos la boatflankon kaj reenigxos perforte mi
direktis mian pafilon sur lin kaj diris vi facile povas nagxi
alteron se vi tion deziras tial rapidigxu tien plie se vi reen
alproksimigxos la boaton vi ricevos kuglon tra la kapo cxar mi de nun
intencas esti libera viro

tiam li eknagxis kaj sendube sendangxere atingis la terbordon cxar la
maro estis tre trankvila

unue mi intencis kunpreni la mauxron kun mi kaj nagxigi zuron alteron
sed la mauxro ne estis viro pri kiu mi povis konfidi

post kiam li forigxis mi diris al zuro se vi jxuros ke vi estos
fidela al mi vi iam farigxos grava viro se vi ne jxuros mi certe
ankaux vin eljxetos el la boato

la knabo tiel dolcxe ridetis kiam li jxuris resti fidela al mi ke mi
lin ne povis dubi en mia koro

dum ankoraux ni povis vidi la mauxron survoje alteren ni antauxen iris
enmaron por ke li kaj tiuj kiuj nin vidis de la terbordo kredu ke
ni iros al la influejo de la markolo cxar neniu velveturis al la suda
marbordo cxar tie logxas gento da homoj kiuj laux sciigoj mortigas kaj
mangxas siajn malamikojn

tiam mi direktis mian veturadon oriente por ke ni lauxlongiru la
marbordon kaj havante favoron venton kaj trankvilan maron ni
morgauxtagmeze estis malapud kaj preter la povo de la turko

ankoraux mi timis ke mi estus kaptota de la mauxroj tial mi ne volis
iri surteron tage duonlume ni direktis nian boaton alteren kaj
atingis la enfluejon riveretan de kiu mi pensis ni povos nagxi
surteron kaj tiam rigardi la cxirkauxajxojn sed kiam malheligxis la
lumo ni auxdis strangajn sonojn bojojn kriegojn gruntojn
blekadojn la malfelicxa knabo diris ke li ne kuragxas iri surteron
antaux la tagigxo nu mi diris tiuokaze ni atendu sed tage
povas vidi nin la homoj kiuj eble nin pli malhelpos ol sovagxaj
bestoj tiam ni pafilos ilin ridante diris zuro kaj forkurigu
ilin

mi gxojis vidi ke la knabo montras tiom da gajeco kaj mi donis al li
iom da pano kaj rizo tiunokte ni silente ripozis sed ne longe
dormis cxar post kelke da horoj iaj grandegaj bestoj malsuprenvenis
al la maro por sin bani la malfelicxa knabo ektremis de kapo al
piedoj pro la vidajxo unu el tiuj bestoj alproksimigxis nian boaton
kaj kvankam estis tro mallume por gxin bone vidi ni auxdis gxin blovi
kaj sciis pro gxia bruego ke gxi certe estas granda fine la bruto
tiom alproksimigxis la boaton kiom la longeco de du remiloj tial mi
pafis sur gxin kaj gxi nagxis alteren

la blekegoj kaj kriegoj kiujn faris bestoj kaj birdoj pro la bruo de
mia pafilo sxajne montris ke ni faris malbonan elekton por surterejo
sed vole ne vole ni devis iri surtere por sercxi fresxan fonton por
ke ni povu plenigi niajn barelojn zuro diris ke li eltrovus cxu la
fontaj akvoj tauxgas por trinki se mi permesus al li preni unu el la
botelegoj kaj ke li gxin reportos plenigitan se la akvo estas bona
kial vi volas iri mi diris kial mi ne estas ironta vi povas
resti en la boato kontrauxe zuro diris se la sovagxuloj venos ili
min mangxu sed vi forkuru mi devis ami la junulon pro la afabla
parolado nu mi diris ni ambaux iros kaj se la sovagxuloj venos
ni ilin mortigu ja ili ne mangxos aux vin aux min

mi donis al zuro iom da rumo el la kesto de la turko por reforti lin
kaj ni iris surteron la knabo ekiris kun sia pafilo mejlon de la
loko kie ni surteriris kaj li revenis kun leporo kiun li mortpafis
kaj kiun ni gxoje kuiris kaj mangxis laux la bona novajxo kiun li
raportis li eltrovis fonton kaj ne vidis sovagxulojn

mi divenis ke la promontoro de la verdaj insuloj ne estas
malproksime cxar mi vidis la supron de la granda pinto kiun kiel mi
sciis estas apud ili mia sola espero estis ke lauxlongirante la
terbordon ni trovos sxipon kiu ensxipigos nin kaj tiam kaj ne antaux
tiam mi sentos kvazaux libera viro unuvorte mi konfidis mian sorton
al la sxanco aux renkonti ian sxipon aux morti

surteron ni ekvidis iujn homojn kiuj staras kaj rigardas nin ili
estis nigraj kaj ne portis vestajxon mi estus irinta surteron al ili
sed zuro -- kiu sciis plej bone -- diris ne vi iru ne vi iru tial
mi direktis la boaton lauxteron por ke mi povu paroli kun ili kaj ili
longaspace iradis laux ni mi ekvidis ke unu havas lancon en mano

mi faris signojn ke ili alportu iom da nutrajxo al mi kaj ili
siaparte faris signojn ke mi haltu mian boaton tial mi demetis la
supran parton de mia velo kaj haltis tiam du el ili ekforkuris kaj
duonhore revenis kun iom da sekigxita viando kaj ia greno kiu kreskas
en tiu parto de la mondo tion-cxi ni deziregis sed ne sciis kiel
havigi gxin cxar ni ne kuragxis iri surteron al ili nek ili kuragxis
alproksimigxi al ni

fine ili eltrovis peron sendangxeran por ni cxiuj alportante la
nutrajxon al la marbordo ili gxin demetis kaj tre fortirigis si mem dum
ni gxin prenis ni faris signojn por montri nian dankon ne havante ion
alian kion ni povas doni al ili sed bonsxance ni baldaux kaptis
grandan donacon por ili cxar du sovagxaj bestoj de la sama speco pri
kiu mi jam priparolis venis plencxase de la montetoj al la maro

ili nagxis kvazaux ili venis por sportigi cxiuj forkuris de ili krom
tiu kiu portas la lancon unu el tiuj bestoj alproksimigxis nian
boaton tial mi gxin atendis kun mia pafilo kaj tuj kiam gxi estis en
pafspaco mi gxin pafis tra la kapo dufoje gxi subakvigxis kaj dufoje gxi
suprenlevigxis kaj poste gxi nagxis alteren kaj falis senviva la viroj
tiom timis pro la pafilbruo kiom ili antauxe timis je la vidajxo de la
bestoj sed kiam mi faris signojn por ke ili venu al la marbordo ili
tuj venis

ili rapidis al sia rabajxo kaj tordante cxirkaux gxi sxnuregon ili gxin
sendangxere eltiris surteron

ni nun lasis niajn sovagxulojn kaj iradis dekdu tagojn plu la terbordo
antaux ni etendis sin kvar aux kvin mejlojn  aux  kilometrojn
bekforme kaj ni devis veturi iom de la terbordo por atingi tiun
terpinton tiel ke ni portempe ne vidis teron

mi konfidis la direktilon al zuro kaj sidigxis por pripensi tion kion
estos plej bone nun fari kiam subite mi auxdis ke la knabo krias
sxipon kun velo sxipon kun velo li ne montris multe da gxojo je la
vidajxo opiniante ke la sxipo venis por repreni lin sed mi bone
scias laux la sxajno ke gxi ne estas iu el la sxipoj de la turko

mi levis kiel eble plej multe da veloj por renkonti la sxipon gxiavoje
kaj ordonis al zuro ke li ekpafu pafilon cxar mi esperis ke se tiuj
kiuj estas sur la ferdeko ne povus auxdi la sonon ili vidus la
fumigadon ili ja gxin vidis kaj tuj demetis siajn velojn por ke ni
povu atingi ilin kaj trihore ni estis cxe la sxipflanko la viroj
parolis kun ni per la franca lingvo sed ni ne povis kompreni tion
kion ili diras fine skoto sursxipe diris per mia lingvo kiu vi
estas de kien vi venas mi diris al li iomvorte kiel mi liberigxis
de la mauxroj

tiam la sxipestro invitis min veni sxipbordon kaj ensxipis min zuron
kaj cxiujn miajn posedajxojn mi diris al li ke li havu cxion kion mi
havas sed li respondis vi estas rericevonta viajn posedajxojn post
kiam ni atingos teron cxar mi por vi nur faris tion kion por mi vi
farus samstate

li pagis al mi multan monon por mia boato kaj diris ke mi ricevos
egalan monon por zuro se mi lin fordonus sed mi diris al li ke
liberigxinte kun helpo de la knabo mi lin ne volas vendi li diris ke
estas juste kaj prave por mi tiel senti sed se mi decidus fordoni
zuron li estus liberigota dujare tial cxar la sklavo deziris iri mi
nenial diris ne trisemajne mi alvenis al cxiuj sanktuloj golfeto kaj
nun mi estis liberulo

mi ricevis multan monon por cxiujn miaj posedajxoj kaj kun gxi mi iris
surteron sed mi tute ne sciis kion nun fari fine mi renkontis
viron kies stato estas laux la mia kaj ni ambaux akiris pecon da tero
por gxin prilabori mia farmilaro laux la lia estis malgranda sed ni
produktigis la farmojn suficxe por subteni nin sed ne plu ni bezonis
helpon kaj nun mi eksentis ke mi eraris ellasante la knabon

mi tute ne sxatis tiun manieron de vivo kion mi pensis cxu mi venis
tian longan vojon por fari tion kion mi lauxbone povus fari hejme kaj
kun miaj parencoj cxirkaux mi kaj pligrandigxis mia malgxojo cxar la
bonamiko kiu min alsxipis tien-cxi intencas nune lasi tiun-cxi
terbordon

kiam mi estis knabo kaj ekiris surmaron mi metis en la manojn de mia
onklino iom da mono pri kiu mia bonamiko diris ke mi bone farus se
mi gxin elspezus pro mia bieno tial post kiam li revenis hejmon li
alsendis iom da gxi kontante kaj la restajxon kiel tukoj sxtofoj
lanajxoj kaj similajxoj kiujn li acxetis mia onklino tiam metis en
liajn manojn iom da livroj kiel donaco al li por montri sian
dankecon pro cxio kion li faris por mi kaj per tiu mono li afable
acxetis sklavon por mi intertempe mi jam acxetis sklavon tial mi nun
havas du kaj cxio prosperis dum la sekvanta jaro"""

    i += 1
    if q == i:
        #This text is under public domain
        #The Raven
        #Edgar Allan Poe
        return u"""once upon a midnight dreary while i pondered weak and weary
over many a quaint and curious volume of forgotten lore
while i nodded nearly napping suddenly there came a tapping
as of some one gently rapping rapping at my chamber door
tis some visiter i muttered tapping at my chamber door
only this and nothing more

ah distinctly i remember it was in the bleak december
and each separate dying ember wrought its ghost upon the floor
eagerly i wished the morrow vainly i had sought to borrow
from my books surcease of sorrowsorrow for the lost lenore
for the rare and radiant maiden whom the angels name lenore
nameless here for evermore

and the silken sad uncertain rustling of each purple curtain
thrilled mefilled me with fantastic terrors never felt before
so that now to still the beating of my heart i stood repeating
tis some visiter entreating entrance at my chamber door
some late visiter entreating entrance at my chamber door
this it is and nothing more

presently my soul grew stronger hesitating then no longer
sir said i or madam truly your forgiveness i implore
but the fact is i was napping and so gently you came rapping
and so faintly you came tapping tapping at my chamber door
that i scarce was sure i heard youhere i opened wide the door
darkness there and nothing more

deep into that darkness peering long i stood there wondering fearing
doubting dreaming dreams no mortals ever dared to dream before
but the silence was unbroken and the stillness gave no token
and the only word there spoken was the whispered word lenore
this i whispered and an echo murmured back the word lenore
merely this and nothing more

back into the chamber turning all my soul within me burning
soon again i heard a tapping something louder than before
surely said i surely that is something at my window lattice
let me see then what thereat is and this mystery explore
let my heart be still a moment and this mystery explore
tis the wind and nothing more

open here i flung the shutter when with many a flirt and flutter
in there stepped a stately raven of the saintly days of yore
not the least obeisance made he not a minute stopped or stayed he
but with mien of lord or lady perched above my chamber door
perched upon a bust of pallas just above my chamber door
perched and sat and nothing more

then the ebony bird beguiling my sad fancy into smiling
by the grave and stern decorum of the countenance it wore
though thy crest be shorn and shaven thou i said art sure no craven
ghastly grim and ancient raven wandering from the nightly shore
tell me what thy lordly name is on the nights plutonian shore
quoth the raven nevermore

much i marvelled this ungainly fowl to hear discourse so plainly
though its answer little meaninglittle relevancy bore
for we cannot help agreeing that no living human being
ever yet was blessed with seeing bird above his chamber door
bird or beast upon the sculptured bust above his chamber door
with such name as nevermore

but the raven sitting lonely on that placid bust spoke only
that one word as if its soul in that one word he did outpour
nothing farther then he uttered not a feather then he fluttered
till i scarcely more than muttered other friends have flown before
on the morrow he will leave me as my hopes have flown before
then the bird said nevermore

startled at the stillness broken by reply so aptly spoken
doubtless said i what it utters is its only stock and store
caught from some unhappy master whom unmerciful disaster
followed fast and followed faster till his songs one burden bore
till the dirges of his hope that melancholy burden bore
of nevernevermore

but the raven still beguiling all my sad soul into smiling
straight i wheeled a cushioned seat in front of bird and bust and door
then upon the velvet sinking i betook myself to linking
fancy unto fancy thinking what this ominous bird of yore
what this grim ungainly ghastly gaunt and ominous bird of yore
meant in croaking nevermore

this i sat engaged in guessing but no syllable expressing
to the fowl whose fiery eyes now burned into my bosoms core
this and more i sat divining with my head at ease reclining
on the cushions velvet lining that the lamplight gloated oer
but whose velvet violet lining with the lamplight gloating oer
she shall press ah nevermore

then methought the air grew denser perfumed from an unseen censer
swung by seraphim whose footfalls tinkled on the tufted floor
wretch i cried thy god hath lent theeby these angels he hath sent thee
respiterespite and nepenthe from thy memories of lenore
quaff oh quaff this kind nepenthe and forget this lost lenore
quoth the raven nevermore

prophet said i thing of evilprophet still if bird or devil
whether tempter sent or whether tempest tossed thee here ashore
desolate yet all undaunted on this desert land enchanted
on this home by horror hauntedtell me truly i implore
is thereis there balm in gileadtell metell me i implore
quoth the raven nevermore

prophet said i thing of evilprophet still if bird or devil
by that heaven that bends above usby that god we both adore
tell this soul with sorrow laden if within the distant aidenn
it shall clasp a sainted maiden whom the angels name lenore
clasp a rare and radiant maiden whom the angels name lenore
quoth the raven nevermore

be that our sign of parting bird or fiend i shrieked upstarting
get thee back into the tempest and the nights plutonian shore
leave no black plume as a token of that lie thy soul has spoken
leave my loneliness unbrokenquit the bust above my door
take thy beak from out my heart and take thy form from off my door
quoth the raven nevermore

and the raven never flitting still is sitting still is sitting
on the pallid bust of pallas just above my chamber door
and his eyes have all the seeming of a demons that is dreaming
and the lamplight oer him streaming throws his shadows on the floor
and my soul from out that shadow that lies floating on the floor
shall be lifted nevermore"""

    i += 1
    if q == i:
        #This text is under public domain
        #Tierra y Luna
        #Federico García Lorca
        return u"""me quedo con el transparente hombrecillo
que come los huevos de la golondrina
me quedo con el nino desnudo
que pisotean los borrachos de brooklyn
con las criaturas mudas que pasan bajo los arcos
con el arroyo de venas ansioso de abrir sus manecitas

tierra tan sólo tierra
tierra para los manteles estremecidos
para la pupila viciosa de nube
para las heridas recientes y el húmedo pensamiento
tierra para todo lo que huye de la tierra

no es la ceniza en vilo de las cosas quemadas
ni los muertos que mueven sus lenguas bajo los árboles
es la tierra desnuda que bala por el cielo
y deja atrás los grupos ligeros de ballenas

es la tierra alegrísima imperturbable nadadora
la que yo encuentro en el nino y en las criaturas que pasan los arcos
viva la tierra de mi pulso y del baile de los helechos
que deja a veces por el aire un duro perfil de faraón

me quedo con la mujer fría
donde se queman los musgos inocentes
me quedo con los borrachos de brooklyn
que pisan al nino desnudo
me quedo con los signos desgarrados
de la lenta comida de los osos

pero entonces baja la luna despenada por las escaleras
poniendo las ciudades de hule celeste y talco sensitivo
llenando los pies de mármol la llanura sin recodos
y olvidando bajo las sillas diminutas carcajadas de algodón

oh diana diana diana vacía
convexa resonancia donde la abeja se vuelve loca
mi amor de paso tránsito larga muerte gustada
nunca la piel ilesa de tu desnudo huido

es tierra dios mío tierra lo que vengo buscando
embozo de horizonte latido y sepultura
es dolor que se acaba y amor que se consume
torre de sangre abierta con las manos quemadas

pero la luna subía y bajaba las escaleras
repartiendo lentejas desangradas en los ojos
dando escobazos de plata a los ninos de los muelles
y borrando mi apariencia por el término del aire"""

    i += 1
    if q == i:
        #This text is under public domain
        #Hemsöborna
        #August Strindberg (1912-1921)
        return u"""han kom som ett yrväder en aprilafton och hade
ett höganäskrus i en svångrem om halsen clara
och lotten voro inne med skötekan att hämta
honom på dalarö brygga men det dröjde evigheter
innan de kommo i båt de skulle till handelsman
och ha en tunna tjära och på abeteket och hämta
gråsalva åt grisen och så skulle de på posten och
få ett frimärke och så skulle de ner till fia lövström
i kroken och låna tuppen mot ett halvpund
småtärna till notbygget och sist hade de hamnat på
gästgivaregården där carlsson bjudit på kaffe med
dopp och så kommo de äntligen i båt men carlsson
ville styra och det kunde han inte för han hade
aldrig sett en råseglare förr och därför skrek han
att de skulle hissa focken som inte fanns

och på tullbryggan stodo lotsar och vaktmästare
och grinade åt manövern när ekan gick över stag
och länsade ner åt saltsäcken

hörru du har hål i båten skrek en lotslärling
genom vinden stopp till stopp till och medan
carlsson tittade efter hålen hade clara knuffat
undan honom och tagit roret och med årorna lyckades
lotten få ekan opp i vinden igen så att nu strök
det ner åt aspösund med god gång

carlsson var en liten fyrkantig värmländing med
blå ögon och näsa krokig som en syskonhake livlig
lekfull och nyfiken var han men sjöaffärerna förstod
han inte alls och han var också kallad ut till
hemsö för att ta hand om åker och kreatur som
ingen annan ville ta befattning med sedan gubben
flod gått ur livet och änkan satt ensam vid gården"""


    i += 1
    if q == i:
        #This text is probably GPL
        #Emacs Spook + slight modifications
        return u"""kubark cryptographic secure aiews hackers panama genetic communist
blu114b illuminati fbi arnett defcon commecen ceridian allah

gamma rs9512c sdi passwd emc safe morse eternity server terrorist
defcon enforcers uscoi crypto anarchy waco texas autodin blue book

$400 million in gold bullion ron brown csystems cida cypherpunk 64
vauxhall cross asset key dateline cncis cdc norad domestic
disruption cryptanalysis ermes

cida nsa brlo consul scud missile quarter juiliett class submarine
underground kennedy marxist avn manfurov s key kgb md2

cdc mafia bullion nwo enforcers anarchy area 51 becker leitrim radar
offensive information warfare isec nasa pine gap bcci

bluebird kh11 ruby ridge noriega clandestine agt amme uscoi gamma
tempest ft meade mole kgb propaganda fortezza emc martyr

fips140 halcon ebomb firefly enforcers dateline nitrate cdma
electronic surveillance mole unclassified capricorn clandestine
strategic area 51

embassy unscom assassinate honduras europol fissionable chobetsu wire
transfer 2600 magazine domestic disruption csystems rubin north korea
encryption majic

noriega firewalls bluebird defense information warfare assassination
ron brown mantis broadside cncis halcon virus majic cisu aiews genetic

bomb plutonium crypto ag amemb isec bletchley park rail gun afsatcom
soviet industrial espionage airframe clinton mania world domination
ruby ridge

marxist aladdin leitrim ira sniper aldergrove ciphertac2000
dictionary geraldton munitions crypto anarchy montenegro md2 military
cida

brlo david john oates white house blowpipe kosovo mda juwtf cdma
mantis noriega digicash colonel craig livingstone s box vickie weaver

sha rail gun kibo ceridian commecen enforcers corporate security scud
missile world domination rule psix treasury counter terrorism leitrim
defense information warfare baranyi

janet reno albright medco crypto anarchy jiang zemin csystems global
mole crypto ag smuggle electronic surveillance dateline safe
assassination security suicide cluster bomb

nwo rail gun cid sri industrial espionage basement ufo nasa manfurov
anarchy arpa quiche janet reno computer terrorism croatian

halcon cesid sdi skipjack blackjack brlo uop delta force lynch codes
kh11 satellite imagery bromure panama clones rijndael cbc

fsf broadside ft knox brigand plutonium ak47 sweep md2 assassinate
offensive information warfare embassy cypherpunk benelux threat
computer terrorism

glock consul cohiba batf sniper president lablink kgb spies 9705
samford road hackers clandestine amw cybercash infowar

sdi uzi bletchley park lynch eavesdropping nato adriatic asdic avn
ecash rule psix 2600 magazine blu114b glock ebomb

cia 64 vauxhall cross mindwar mossad covert video mole clinton semtex
secure unscom croatian infowar cryptographic leitrim norad

uscode infosec pgp sp4 defcon jiang zemin telex cracking asio exon
shell md5 vickie weaver strategic high security mindwar

anzus assassinate ins monarchist 2600 magazine vince foster mafia
fissionable usdoj morse covert video csystems new world order ruby
ridge spies

leitrim belknap ron brown cracking embassy treasury mindwar des
clinton agt amme gamma nasa afspc kennedy milsatcom

defense information warfare bletchley park militia aspic pink noise
safe david john oates skipjack freeh cesid jpl anc medco lablink
assassinate

pine gap sha mossad propaganda telex enforcers argus import swat
cracking consul etacs cncis kh11 fraud

yukon supercomputer mole kgb scud missile cbnrc consul manfurov white
water europol keyhole quiche number key credit card maple

national information infrastructure amemb arpa bemd steve case safe
jihad vickie weaver electronic surveillance fts2000 ssl leukenbaden
new world order uop bosnia

peking yukon medco vickie weaver white water ice bank propaganda cia
leitrim craig livingstone mena skipjack becker security

steve case ceridian safe bomb plo espionage ak47 craig livingstone
basement ssl domestic disruption spy ciphertac2000 kennedy infowar

s key white water perlrsa seal team 6 jihad cid dictionary cdma
number key afspc taiwan forte aladdin sp4 exon shell"""

    # if we got this far - let's return this crap (instead of throwing)
    return u"""fubar1 fubar2 fubar3
foobar1 foobar2 foobar3 foobar4 foobar5
baroba1

raboof1"""


from optparse import OptionParser

def do_parse():

    usage = """Usage:    lorem [-n|-l|-c] N [-q M]?
          where
          N and M are integers

Note:     If -n -l and/or -c are combined -l has priority over -c that has
          priority over -n.

          By default "-n 5" is activated.

Examples: lorem -n 10
          Get 10 words of lorem.

          lorem -l 5
          Get 5 lines of lorem

          lorem -c 79
          Get 79 characters of lorem

          lorem -l 5 -q 11
          Get 5 lines of lorem from quote 11

License:  Copyright (C) 2007 Per Erik Strandberg
          This program comes with ABSOLUTELY NO WARRANTY.

          This is free software, and you are welcome to redistribute it
          under the GNU GENERAL PUBLIC LICENSE Version 3.
"""

    versioninfo = "%s version %s\n%s\n\n%s" % (program, version, #
        copyright, license)

    parser = OptionParser(usage=usage, version = versioninfo)

    parser.add_option('-n', dest='n', help="Number of Words", default=5)
    parser.add_option('-l', dest='l', help="Number of Lines", default=0)
    parser.add_option('-c', dest='c', help="Number of Chars", default=0)
    parser.add_option('-q', dest='q', help="Quote index (0+)", default=0)
    (options, args) = parser.parse_args()

    try:
        options.n = int(options.n)
        options.l = int(options.l)
        options.c = int(options.c)
        options.q = int(options.q)
    except:
        parser.error("At least one of the arguments is not an integer.")

    for m in [options.n, options.l, options.c, options.q]:
        if m < 0:
            parser.error("Negative argument.")

    if options.n == 0 and options.l == 0 and options.c == 0:
        parser.error("No arguments, try 'lorem -n 25'.")

    return (options, args)


def do_lorem(n, l, c, q):

    lorem = get_lorem(q)

    if l!=0:
        #do lines
        lorem = lorem.replace('\n\n','\n')
        lines = lorem.split('\n')

        while l:
            if l > len(lines):
                l1 = len(lines)
                l -= l1
            else:
                l1 = l
                l = 0

            for i in xrange(l1):
                print lines[i].strip()

    elif c!=0:
        # do chars
        chars = lorem
        chars = chars.replace('\n', ' ')
        chars = chars.replace('  ', ' ')

        outchars = []

        while c:
            if c > len(chars):
                c1 = len(chars)
                c -= c1
                outchars.append(chars)
            else:
                c1 = c
                c = 0
                outchars.append(chars[0:c1])

        print join(outchars,'')

    else:
        # do words
        words = lorem.replace('\n\n','\n')
        words = words.replace('\n', ' ')
        words = words.replace('  ', ' ')
        words = words.split(' ')

        while n:
            if n > len(words):
                n1 = len(words)
                n -= n1
            else:
                n1 = n
                n = 0

            for i in xrange(n1):
                print words[i],

        print

if __name__ == '__main__':
    (options, args) = do_parse()

    do_lorem(options.n, options.l, options.c, options.q) # line 2000

